theme: jekyll-theme-chirpy

lang: en
timezone: America/Chicago

title: Hiram Martinez
tagline: IT Support | Sysadmin
description: IT support professional. Helpdesk, sysadmin, home lab enthusiast.

url: "https://hiramatx.github.io"

github:
  username: hiramatx

social:
  name: Hiram Martinez
  email: hiram.martinez@gmail.com
  links:
    - https://github.com/hiramatx
    - https://www.linkedin.com/in/hiram-martinez/

avatar: /assets/images/avatar.jpg

comments:
  active: false
