title: Hiram Martinez
tagline: IT Support | Sysadmin
description: IT support professional. Helpdesk, sysadmin, home lab enthusiast.

url: "https://hiramatx.github.io"
baseurl: ""

timezone: America/Chicago
lang: en

author:
  name: Hiram Martinez
  email: hiram.martinez@gmail.com

social:
  github: hiramatx
  linkedin: hiram-martinez

avatar: /assets/images/avatar.jpg

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
